using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: AssemblyConfigurationAttribute("")]
[assembly: AssemblyCompanyAttribute("Cirque du Soleil Inc.")]
[assembly: AssemblyProductAttribute("CDS.Framework.Tools.Colibri")]
[assembly: AssemblyCopyrightAttribute("Copyright CDS 2009")]
[assembly: AssemblyTrademarkAttribute("")]
[assembly: AssemblyCultureAttribute("")]
[assembly: AssemblyVersionAttribute("9.11.6.5796")]
[assembly: AssemblyFileVersionAttribute("9.11.6.5796")]

